### ISSUE TITLE
Crafty crashing when searching recipes with the word "slice"

### ISSUE THREAD

**Issue by GetAwayCoxn** [mousseng/xitools#23]
Every time I type the word "slice" into the recipe search I crash the addon.

![image](https://github.com/mousseng/xitools/assets/66495755/a325ef3d-a191-4379-8232-479d21cb942d)

**Comment by GetAwayCoxn** [comment]
Typing in "map" when looking for maple crashes as well. Same crash and line number

**Comment by mousseng** [comment]
ah. dastardly metatables. thanks, should be fixed in latest master

**Comment by GetAwayCoxn** [comment]
Since this issue is still in Open status I'll just drop this here, same error, same line number, different cause. Seems any use of a capital letter in the recipes search will cause this to crash too.
![image](https://github.com/mousseng/xitools/assets/66495755/95116434-e1c9-4d2d-9c11-2d25255e8e22)

**Comment by mousseng** [comment]
not _quite_ a year later, but i have fixed this other issue
